repos:
-   repo: local
    hooks:
    -   id: ruff-check
        name: ruff-check
        entry: uv run ruff check --fix .
        language: system
        pass_filenames: false
    -   id: ruff-format
        name: ruff-format
        entry: uv run ruff format .
        language: system
        pass_filenames: false
    # -   id: ty-check
    #     name: ty-check
    #     entry: uv run ty check .
    #     language: system
    #     pass_filenames: false
